# Site settings
title: Peter D. Kaizer
email: pdkaizer@gmail.com
description: "Peter D. Kaizer: Digital Strategist, User Experience Architect, Front-end Developer, Mac Evangelist, Foodie, Dad, Husband"
baseurl: ""
url: "http://peterkaizer.com"

# Build settings
markdown: kramdown
permalink: /:title
paginate: 6
